apiVersion: v1
kind: Service
metadata:
  name: su-admin-service
  labels:
    app: su-admin-service
spec:
  type: LoadBalancer
  selector:
    app: su-admin-service
  ports:
    - name: "8920"
      port: 8920
      targetPort: 8920
    - name: "8921"
      port: 8921
      targetPort: 8921