# Bootstrap.yml is loaded before application.yml. So any info that is needed for any application*.yml,
# needs to be put here
spring:
  application:
    name: "discovery-service"
#  cloud:
#    config:
#      fail-fast: true
  config:
#    https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_quick_start
#    import: optional:configserver:http://su-config-service:8900,optional:configserver:http://localhost:8900
    import: optional:configserver:http://localhost:8900?max-attempts=10&max-interval=30000&multiplier=1.4&initial-interval=1100,optional:configserver:http://su-config-service:8900?max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

# sTILL NOT WORKING!!!!!!!!!!!!