# Bootstrap.yml is loaded before application.yml. So any info that is needed for any application*.yml,
# needs to be put here
spring:
  application:
    name: "discovery-service"
  config:
#    https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_quick_start
    import: optional:configserver:http://su-config-service:8900,optional:configserver:http://localhost:8900