spring:
  application:
    name: "admin-service"
  profiles:
    active: management,logging
  config:
    import: optional:configserver:http://localhost:8900

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8910/eureka
    registry-fetch-interval-seconds: 5