spring:
  application:
    name: demo-service
  banner:
    location: classpath:/service-universe-banner.txt

  profiles:
    active: management,logging
  config:
    import: optional:configserver:http://localhost:8900