apiVersion: v1
kind: Service
metadata:
  name: su-discovery-service
  labels:
    app: su-discovery-service
spec:
  type: LoadBalancer
  selector:
    app: su-discovery-service
  ports:
    - name: "8910"
      port: 8910
      targetPort: 8910
    - name: "8911"
      port: 8911
      targetPort: 8911