management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      group:
        custom:
          include:
            - diskSpace
            - ping
          show-components: always
          show-details: always
    env:
      enabled: true
      show-values: always