management:
  endpoint:
    health:
      group:
        custom:
          include:
            - diskSpace
            - ping
          show-components: when_authorized
          show-details: when_authorized